{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demo-web
  namespace: demo
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.className | quote }}
    alb.ingress.kubernetes.io/scheme: {{ .Values.ingress.scheme | quote }}
    alb.ingress.kubernetes.io/target-type: {{ .Values.ingress.targetType | quote }}

    # ExternalDNS: auto-create Route53 record -> ALB
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.ingress.hostname | quote }}

    {{- if and .Values.ingress.tls.enabled .Values.ingress.tls.acmCertificateArn }}
    # TLS (HTTPS) via ACM on the ALB
    alb.ingress.kubernetes.io/certificate-arn: {{ .Values.ingress.tls.acmCertificateArn | quote }}
    alb.ingress.kubernetes.io/listen-ports: {{ .Values.ingress.tls.listenPorts | quote }}
    alb.ingress.kubernetes.io/ssl-redirect: {{ .Values.ingress.tls.sslRedirect | quote }}
    {{- end }}
spec:
  rules:
  - host: {{ .Values.ingress.hostname | quote }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: demo-web
            port:
              number: {{ .Values.service.port }}
{{- end }}
